gText_Birch_Welcome::
	.string "Sorry to keep you waiting!\p"
	.string "Let me introduce myself,\n"
	.string "I'm Professor Mike.\p"
	.string "But you can call me Gump.\p"
	.string "Pleasure to meet you!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "As I understand it, you're\n"
	.string "something of a Pokémon fan.\p"
	.string "Tell ya what, here's someone\n"
	.string "I think you should meet.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is my partner: Rotom.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "You may not know this but Rotom\n"
	.string "aren't normally from this region.\p"
	.string "You see, someone has quite drastically\n"
	.string "changed the world you're entering.\p"
	.string "All sorts of new Pokémon have began\n"
	.string "populating the region's wildlife.\p"
	.string "Aspects of life that were once a\n"
	.string "burden are now easy and convenient.\p"
	.string "Trainers that were once easy and\n"
	.string "forgettable are now more challenging\l"
	.string "and fun to battle!\p"
	.string "My hypothesis is that these changes\n"
	.string "were made with you in mind.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "To be clear, this IS you…\n"
	.string "right?\p"
	.string "{PLAYER}?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "Yeah, you're definitely {PLAYER}!\p"
	.string "You match the description I\n"
	.string "have here to a tee.\p"
	.string "Long brown hair…\p"
	.string "Beautiful smile…\p"
	.string "Awkawrd pose…\p"
	.string "To a tee!\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "Anyways, as I was saying…\p"
	.string "{PLAYER}, I've got a favor to ask.\p"
	.string "Can you please explore this new world\n"
	.string "and find out if my theory's correct.\p"
	.string "Whoever did all this obviously put\n"
	.string "their heart into it and I'd hate to\l"
	.string "see all that hard work go to waste.\p"
	.string "Can you do that for me?\p"
	.string "Great!\p"
	.string "I promise, you won't regret it.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Alrighty then, you ready?\p"
	.string "Then go forth and begin your\n"
	.string "adventure!\p"
	.string "Leave no stone unturned.\p"
	.string "Leave no challenge unanswered.\p"
	.string "And when you get there, find my son.\p"
	.string "He'll help get you started.\p"
	.string "See you soon!\p"
	.string "$"
