gText_Birch_Welcome::
	.string "Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "I'm Professor Mike.\n"
	.string "But you can call me Gump.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is my partner: Rotom.{PAUSE 96}\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "You may not know this but Rotom\n"
	.string "aren't normally found in Hoenn.\p"
	.string "You see, someone has quite drastically\n"
	.string "changed the world you're entering.\p"
	.string "All sorts of new Pokémon have began\n"
	.string "populating the region's wildlife.\p"
	.string "Aspects of life that were once a\n"
	.string "burden are now easy and convenient.\p"
	.string "Trainers that were once easy and\n"
	.string "forgettable are now more challenging\l"
	.string "and fun to battle!\p"
	.string "My hypothesis is that these changes\n"
	.string "were made with you in mind.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "This is you, right?\n"
	.string "Yeah, your name is {PLAYER}!\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Well {PLAYER}, you've got some work\n"
	.string "cut out for ya.\p"
	.string "It'll take you exploring this new\n"
	.string "world to see if my theory's correct.\p"
	.string "Whoever made this world has put\n"
	.string "their heart into every change.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "So leave no stone unturned.\p"
	.string "Leave no challenge unanswered.\p"
	.string "Are you ready?\p"
	.string "Then go forth and begin your\n"
	.string "adventure!\p"
	.string "When you get there, find my son.\n"
	.string "He'll help get you started.\p"
	.string "$"
