gTrickHouse_Mechadoll_Oddish::
	.string "Pichu$"

gTrickHouse_Mechadoll_Poochyena::
	.string "Ponyta$"

gTrickHouse_Mechadoll_Taillow::
	.string "Yamper$"

gTrickHouse_Mechadoll_Azurill::
	.string "Azurill$"

gTrickHouse_Mechadoll_Lotad::
	.string "Corsola$"

gTrickHouse_Mechadoll_Wingull::
	.string "Dewpider$"

gTrickHouse_Mechadoll_Dustox::
	.string "Dustox$"

gTrickHouse_Mechadoll_Zubat::
	.string "Zubat$"

gTrickHouse_Mechadoll_Nincada::
	.string "Dewpider$"

gTrickHouse_Mechadoll_Ralts::
	.string "Cubone$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "Boltund$"

gTrickHouse_Mechadoll_Slakoth::
	.string "Blaziken$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "Magnemite$"

gTrickHouse_Mechadoll_Shroomish::
	.string "Yamper$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "Rotom$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "Greedent$"

gTrickHouse_Mechadoll_Zubat2::
	.string "Diggersby$"

gTrickHouse_Mechadoll_Carvanha::
	.string "Garbodor$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "Repel$"

gTrickHouse_Mechadoll_HarborMail::
	.string "Poké Doll$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Same price$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥300$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥100$"

gTrickHouse_Mechadoll_Nothing::
	.string "Nothing$"

gTrickHouse_Mechadoll_CostMore::
	.string "In a hand$"

gTrickHouse_Mechadoll_CostLess::
	.string "In a bush$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "Same price$"

gTrickHouse_Mechadoll_Male::
	.string "20$"

gTrickHouse_Mechadoll_Female::
	.string "24$"

gTrickHouse_Mechadoll_Neither::
	.string "30$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "46$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "48$"

gTrickHouse_Mechadoll_SameNumber::
	.string "50$"

gTrickHouse_Mechadoll_None::
	.string "3$"

gTrickHouse_Mechadoll_One::
	.string "5$"

gTrickHouse_Mechadoll_Two::
	.string "6$"

gTrickHouse_Mechadoll_Two2::
	.string "I Love You Too Much$"

gTrickHouse_Mechadoll_Three::
	.string "You Are My Sunshine$"

gTrickHouse_Mechadoll_Four::
	.string "All of Me$"

gTrickHouse_Mechadoll_Six::
	.string "Catwalks$"

gTrickHouse_Mechadoll_Seven::
	.string "Foyer$"

gTrickHouse_Mechadoll_Eight::
	.string "FaceTime$"

gTrickHouse_Mechadoll_Six2::
	.string "“Yes!”$"

gTrickHouse_Mechadoll_Seven2::
	.string "“No!”$"

gTrickHouse_Mechadoll_Eight2::
	.string "“Is this a joke?”$"
