PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_MichealBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledMichealOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_MichealBecameGymLeader:
	.string "Micheal became our town's new\n"
	.string "Gym Leader.\p"
	.string "I think he came over with his family\n"
	.string "from somewhere far away.$"

PetalburgCity_House2_Text_BattledMichealOnce:
	.string "I battled Micheal once, but, whew,\n"
	.string "he was way too strong.\p"
	.string "How would I put it?\p"
	.string "I just got the feeling that he\n"
	.string "lives for battling.$"

